// Импорт типа Metadata для настройки метаданных страницы
import type { Metadata } from "next";
// Импорт шрифта Manrope из Google Fonts через Next.js
import { Manrope } from "next/font/google";
// Импорт глобальных стилей приложения
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";

// Настройка шрифта Manrope с созданием CSS переменной для использования в стилях
const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

// Метаданные приложения (заголовок и описание для SEO)
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Корневой layout компонент приложения
 * Оборачивает все страницы и предоставляет общую структуру HTML
 * @param {React.ReactNode} children - Дочерние компоненты (содержимое страниц)
 * @returns {JSX.Element} HTML структуру с подключенными шрифтами
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Применение CSS переменной шрифта Manrope к body для использования во всем приложении */}
      <body className={manrope.variable}>
        <Header />
        <div>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
